baseurl = "louismaiden.netlify.com"
theme = "cocoa-hugo-theme-master"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Alexis Tacnet"
title = "Louis Maiden"
disqusshortname = ""
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Example blog"
copyright = "Copyright © 2020 Louis Maiden"
logofile = "img/music_brain.png"
faviconfile = ""
highlightjs = true
progressively = true
align_left = false
lang = "en"
github = "example"
email = "louismaiden@example.com"
linkedin = "john-example-aa80ue8è"
twitter = "example"
social_banner = "img/banner.png"
posts_navigation = true
small_banner_logo = false