---
title: "Popular Music Is Getting More Depressing Over Time"
author: ''
date: '2018-10-09'
output:
  html_document:
    df_print: paged
slug: popular-music-is-getting-more-depressing-over-time
tags: []
categories: []
---


# Chart-topping songs are getting more depressing over time

Feeling down lately? It could be the music you're listening to.


```{r results='asis', echo=FALSE, include=FALSE,}
library(dplyr)
library(ggplot2)
library(hrbrthemes)
library(plotly)
library(highcharter)
library(moderndive)

load("C:/Users/nyulo/Documents/R/blogg/tracks_subset")
```

```{r results='asis', echo=FALSE, include=FALSE,}
lm <- lm(valence ~ release_year, data = tracks_subset)
summary(lm)
```

# Interactive Graph

```{r, echo = FALSE, warning=FALSE, message = FALSE}

avg_line <- get_regression_points(lm) %>% 
  rename(x = release_year, y = valence_hat) %>% 
  select(x,y)

tracks2 <- tracks_subset %>% 
  filter(!is.na(release_year)) %>% 
  mutate(decade = release_year - release_year %% 10) %>%
  rowwise %>% 
  mutate(tooltip = paste0('<b>Artist:</b> ', artist_name,
                          '<br><b>Track:</b> ', track_name,
                          '<br><b>Album:</b> ', album_name,
                          '<br><b>Valence:</b> ', valence)
         ) %>% ungroup()

hchart(tracks2, 'scatter', hcaes(x = release_year, y = valence)) %>% 
  hc_tooltip(formatter = JS(paste0("function() {return this.point.tooltip;}")), useHTML = T) %>% 
  hc_add_series(data = avg_line, type = 'line', color = 'black') %>%
  hc_colors('lightgrey') %>%
  hc_xAxis(max = 2018, min = 1960, title = list(text = '')) %>% 
  hc_yAxis(max = 1, title = list(text = 'Valence')) %>% 
  hc_title(text = 'Chart-topping Songs Are Getting More Depressing Over Time') %>% 
  hc_subtitle(text = '(1960 - 2018)') %>% 
  hc_add_theme(hc_theme_smpl())


```

# Lowess Curve

```{r, echo = FALSE, warning=FALSE, message = FALSE}


p1 <- tracks_subset %>% 
  ggplot(aes(release_year, valence)) +
  geom_smooth() +
  geom_point(aes(text = paste0("\"", track_name, "\"", " by ", artist_name)),alpha = .1) +
  theme_ipsum_rc() +
  theme(panel.grid = element_blank()) +
  labs(title = "Song Valence for Entire Period",
         subtitle = "1960 - 2018")

ggplotly(p1)


```

