---
title: tennis_one_handed_backhand
author: ''
date: '2019-05-04'
slug: tennis-one-handed-backhand
categories: []
tags: []
---


```{r results='asis', echo=FALSE, include=FALSE, message = FALSE}
library(tidyverse)
library(lubridate)
library(hrbrthemes)
library(ggthemes)
library(scales)
theme_set(theme_ipsum_rc() +
          theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
          theme(axis.title.y = element_text(angle = 0)))
load("C:/Users/nyulo/Documents/HBS/LM/tennis_rankings/data/atp_top_100.R")
```

## Like Tennis's One-Handed Backhand? It Could Be Gone By 2030 

```{r results='asis', echo=FALSE}
# ONE HANDED BACKHAND - EXTENDED MODEL
clean %>% 
  filter(year >= 2000) %>% 
  group_by(year) %>% 
  summarize(share = mean(one_hander, na.rm = TRUE)) %>% 
  ggplot(aes(year, share)) +
  geom_point(size = 2) +
  stat_smooth(method = "lm", fullrange = TRUE) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  expand_limits(y = 0) +
  xlim(c(2000,2030)) +
  geom_hline(yintercept = 0, linetype = 2) +
  scale_y_continuous(labels = percent_format()) +
  labs(x = "", y = "", color = "", title = "Average Share of One-Handers in ATP Top 100 by Year")
```



## About The Dataset

# DISTRIBUTION OF MISSING ONE HANDED BACKHANDS OVER TIME

```{r results='asis', echo= TRUE}

clean %>% 
  ggplot(aes(year, fill = is.na(one_hander))) +
  geom_density(alpha = .8) +
  labs(title = "Distribution of Missing Backhand Method by Year",
       fill = "Missing")
```

# ARE THE MISSING BANDHANDS CORRELATED WITH RANK?

```{r}

clean %>% 
  mutate(Ranking = parse_number(Ranking)) %>% 
  group_by(Ranking) %>% 
  summarize(missing_share = sum(is.na(one_hander))) %>% 
  ggplot(aes(Ranking, missing_share)) +
  geom_line(size = 1.7) +
  expand_limits(y = 0) +
  labs(title = "Sum of Missing Counts By Ranking")
```

# ONE HANDED BACKHAND SHARE BY YEAR

```{r, message = FALSE}
clean %>% 
  filter(year >= 2000) %>% 
  group_by(date) %>% 
  summarize(share = mean(one_hander, na.rm = TRUE)) %>% 
  ggplot(aes(date, share)) +
  geom_smooth(size = 1.7) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  labs(x = "", y = "", color = "", title = "Average Share of One Handers by Year")
```

# ONE HANDED BACKHAND RATE: TOP 50 VS 51 - 100

```{r}
clean %>% 
  filter(year >= 2000) %>% 
  group_by(year, rank_cohort) %>% 
  summarize(share = mean(one_hander, na.rm = TRUE)) %>% 
  ggplot(aes(year, share, color = as.factor(rank_cohort))) +
  geom_smooth(se = FALSE, size = 1.7) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  scale_y_percent() +
  labs(x = "", y = "", color = "", title = "Percent of One Handed Backhands in ATP Top 100")
```

# Again

```{r results='asis', echo=FALSE}
# ONE HANDED BACKHAND - EXTENDED MODEL
clean %>% 
  filter(year >= 2000) %>% 
  group_by(year) %>% 
  summarize(share = mean(one_hander, na.rm = TRUE)) %>% 
  ggplot(aes(year, share)) +
  geom_point(size = 2) +
  stat_smooth(method = "lm", fullrange = TRUE) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  expand_limits(y = 0) +
  xlim(c(2000,2030)) +
  geom_hline(yintercept = 0, linetype = 2) +
  labs(x = "", y = "", color = "", title = "Average Share of One-Handers in ATP Top 100 by Year")
```