---
title: Zipcode Level Impact of COVID19 on the NYC Restaurant Industry
author: Louis Maiden
date: '2020-05-18'
slug: zipcode-level-impact-of-covid19-on-the-nyc-restaurant-industry
categories: []
tags: []
---


```{r results='asis', echo=FALSE, include=FALSE}

library(tidyverse)
library(leaflet)
library(leaflet.extras)
library(htmlwidgets)
library(broom)
library(httr)
library(tigris)
library(rgdal)
library(googleway)


key1 <- "AIzaSyCpI4_qbUAzmxW8XdMzdKSzH3kOZKk9Q_s"

#nyc_zip_names <- c("Financial District", "Battery Park City", "Chelsea")

#nyc_zip_names <- c("Financial District", "Battery Park City", "Chelsea", "West Village", "East VIllage", "Civic Center")
nyc_zip_names <- c("Financial District","Battery Park City", "Chelsea", "West Village", "East Village", "Tribeca", "Lower East Side",
                   "Greenwich Village", "Gramercy", "Flatiron District","Stuyvesant Town", "Kips Bay", "Midtown", "Murray Hill",
                   "Theater District", "Hell's Kitchen", "SoHo", "NoHo", "Little Italy", "Nolita", "Upper East Side", "Upper West Side",
                   "East Harlem","Harlem", "Morningside Heights", "Washington Heights", "Inwood")

shell <- tibble()

for(zip_name in nyc_zip_names) {
  
  #zip_name <- gsub(" ", "_", zip_name)
  
  zip_name <- print(zip_name)
  
  # PULL DATA 1
  api_result1 <- google_places(search_string = paste0("Restaurants in ", zip_name, ",New York"), key = key1)
  print("FIRST API PULLED")
  
  temp1 <- api_result1 %>% 
    .$results %>% 
    as_tibble() %>% 
    janitor::clean_names() %>% 
    select(name, business_status, price_level, place_id, rating, types) %>% 
    mutate(lat = api_result1$results$geometry$location$lat,
           lng = api_result1$results$geometry$location$lng,
           open = business_status == "OPERATIONAL")
  print("FIRST DF SAVED")
  
  token1 <- api_result1$next_page_token
  print("FIRST TOKEN SAVED")

  
  shell <- bind_rows(shell, temp1)
  
}
```


```{r results='asis', echo=FALSE, include=FALSE}
pal <- colorFactor(c("red","blue"), domain = c(TRUE, FALSE))

r <- GET('http://data.beta.nyc//dataset/0ff93d2d-90ba-457c-9f7e-39e47bf2ac5f/resource/35dd04fb-81b3-479b-a074-a27a37888ce7/download/d085e2f8d0b54d4590b1e7d1f35594c1pediacitiesnycneighborhoods.geojson')
nyc_neighborhoods <- readOGR(content(r,'text'), 'OGRGeoJSON', verbose = F)

nyc_restaurants <- shell
coordinates(nyc_restaurants) <- ~lng + lat
proj4string(nyc_restaurants) <- proj4string(nyc_neighborhoods)
matches <- over(nyc_restaurants, nyc_neighborhoods)
points <- cbind(shell, matches) %>% as_tibble()


avgs_by_neighborhood <- points %>% 
  mutate(closed = business_status == "CLOSED_TEMPORARILY") %>% 
  group_by(neighborhood) %>% 
  summarize(closure_rate = mean(closed),
            n = n()) %>% 
  filter(n > 10)

points <- points %>% 
  group_by(neighborhood) %>% 
  mutate(n = n()) %>% 
  ungroup() %>% 
  filter(n >= 10)


map_data <- geo_join(nyc_neighborhoods, avgs_by_neighborhood, "neighborhood", "neighborhood")

nyc_neighborhoods@data <- nyc_neighborhoods@data %>% as_tibble() %>% 
  inner_join(points %>% select(name, business_status, neighborhood)) %>% 
  select(name, neighborhood, everything()) %>% 
  mutate(closed = business_status == "CLOSED_TEMPORARILY") %>% 
  group_by(neighborhood) %>% 
  mutate(closure_rate = mean(closed),
         sample_size = n()) %>% 
  ungroup()

closure_pal <- colorNumeric(c("Reds"), domain  = nyc_neighborhoods@data$closure_rate)


closure_map <- nyc_neighborhoods %>% 
  leaflet() %>% 
  addProviderTiles("CartoDB.Positron") %>% 
  addPolygons(data = map_data, weight = 2, fillOpacity = .4, 
              group = "neighborhood",
              color = ~closure_pal(closure_rate),
              popup = ~paste0("<b>", neighborhood, "</b>", "<br>",
                              "Closure Rate: ", paste0(round(closure_rate, 2), "%"), "<br>",
                              "Neighborhood Sample Size: ", n)) %>% 
  setView(-73.9840, 40.7549, zoom = 11)
```


```{r}
closure_map
````


